### ISSUE TITLE
provider的配置启动后有两个端口起来

### ISSUE THREAD

**Issue by honestAnt** [teaey/spring-boot-starter-dubbo#1]
这个插件引进去后，运行application后悔启动两个个端口。个人觉得provider一方没必要使用boot，原生的spring+dubbo配置就ok了，再套一层boot感觉有点多余

**Comment by teaey** [comment]
一个web，一个dubbo服务端口

**Comment by honestAnt** [comment]
provider一方为何需要一个web端口呢？暴露一个dubbo的端口就ok了呀？

**Comment by teaey** [comment]
web端口是你自己起的哦，本项目不会启动web端口
