### ISSUE TITLE
集成了spring-boot-dubbo aop失效

### ISSUE THREAD

**Issue by alibasediff** [teaey/spring-boot-starter-dubbo#146]
![image](https://cloud.githubusercontent.com/assets/7346210/22107036/bdc7e4d4-de86-11e6-93c0-7212f85ab065.png)

集成了spring-boot-dubbo aop失效

配置文件：
spring.dubbo.application.name=provider
spring.dubbo.registry.address=zookeeper://;zookeeper://;zookeeper://~
spring.dubbo.registry.timeout=2000
spring.dubbo.registry.file=E:\dubbo
spring.dubbo.protocol.name=dubbo
spring.dubbo.protocol.port=20880
spring.dubbo.scan=com.pay

发现其主要原因如下：
![image](https://cloud.githubusercontent.com/assets/7346210/22179809/fb3d53bc-e098-11e6-9e7f-a594871ae1b6.png)

**Comment by hankeqi** [comment]
配置文件：
spring.dubbo.application.name=provider
spring.dubbo.registry.address=zookeeper://~;zookeeper://~;zookeeper://~
spring.dubbo.registry.timeout=2000
spring.dubbo.registry.file=E:\dubbo
spring.dubbo.protocol.name=dubbo
spring.dubbo.protocol.port=20880
spring.dubbo.scan=com.pay

**Comment by teaey** [comment]
1. dubbo服务是否正常工作
1. 没有继承dubbo的时候，拦截器是否正常工作

**Comment by rongmin** [comment]
@teaey  so you think your framework should not impact AOP mechanism ?  your framework(idea) is so good that i want to implement it on production.

**Comment by alibasediff** [comment]
谢谢已找到原因

**Comment by jl9n** [comment]
2216754109

**Comment by githubzouqf** [comment]
305598950

**Comment by teaey** [comment]
rongmin ofcuse
