### ISSUE TITLE
@Service与@Transactional事务冲突

### ISSUE THREAD

**Issue by BingjieLi** [teaey/spring-boot-starter-dubbo#231]
在使用过程中发现通过@Service方式发布的dubbo服务和Spring提供的@Transactional会冲突，求解决方案！

**Comment by eonezhang** [comment]
@BingjieLi 能不能详细点，最好提供sample github repo,这样才好帮助你

**Comment by teaey** [comment]
See:https://github.com/alibaba/dubbo/commit/3945b83956debcf2127606ef6d88a6d29a080094
