### ISSUE TITLE
@service 加入@Transactional 时，解决方案来了！

### ISSUE THREAD

**Issue by rememberber** [teaey/spring-boot-starter-dubbo#241]
**需要修改dubbo源码如下：**
**需要修改的类（接口）**：com.alibaba.dubbo.config.annotation.Service

在类声明的上方加上@Inherited，如下所示：
@Inherited
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
public @interface Service {
……}

**需要注意的是**：
在声明dubbo服务的注解中要加上interfaceName，
或者interfaceClass
如下所示：
@Service(version = "1.0.0",interfaceName="com.xxx.xxx.XxxService")
或者
@Service(version = "1.0.0",interfaceClass = Xxx.class)

在此，也**恳请 @teaey 修改一下，发布新的中央仓库版本**，
然后我们就不用再做此更改了！
非常感谢！！

-------------------
**详情参考**：
http://blog.csdn.net/verne_feng/article/details/53022088

**Comment by teaey** [comment]
Got！

**Comment by teaey** [comment]
See: https://github.com/alibaba/dubbo/commit/3945b83956debcf2127606ef6d88a6d29a080094

**Comment by rememberber** [comment]
@teaey Sorry buddy, and thanks a lot for invite!!
that's not my blog~
just find it over Baidu,and my project need to do so.

thanks again, and looking forward to future co-operation.

**Comment by teaey** [comment]
@rememberber niubility
