### ISSUE TITLE
DubboHolderListener的意义是啥？

### ISSUE THREAD

**Issue by roc-cn** [teaey/spring-boot-starter-dubbo#295]
io.dubbo.springboot.DubboHolderListener
这个Holder线程有啥意义吗！？
在boot中，注册钩子是不是等效？
`ApplicationContext ac = applicationBuilder.registerShutdownHook(true).application().run(args);`

@teaey

**Comment by teaey** [comment]
可以把你的实现，PR上来

**Comment by roc-cn** [comment]
我就是 在boot 的启动类 main方法中
`ApplicationContext ac = applicationBuilder.registerShutdownHook(true).application().run(args);`
注册spring的ApplicationContext的shutdownHook

利用boot自身机制，安全关闭容器。dubbo的服务也可顺利反注册！
@teaey
