### ISSUE TITLE
dubbo是否支持netty协议？

### ISSUE THREAD

**Issue by zhuyanxuan** [teaey/spring-boot-starter-dubbo#305]
整合后的项目也支持dubbo的其他协议吗？

**Comment by 15174834** [comment]
目前支持的协议如下
http://dubbo.io/user-guide/reference-protocol/dubbo.html
7.1 dubbo://
7.2 rmi//
7.3 hessian://
7.4 http://
7.5 webservice://
7.6 thrift://
7.7 memcached://
7.8 redis://

**Comment by teaey** [comment]
netty 只是个io框架。dubbo本身底层使用的netty去通信的。
