### ISSUE TITLE
消费者先启动，提供者后启动，消费者@reference就一直NullPointerException了

### ISSUE THREAD

**Issue by 15174834** [teaey/spring-boot-starter-dubbo#308]
消费者先启动，提供者后启动，消费者@reference就一直NullPointerException了

**Comment by nice2mu** [comment]
这个问题太重要了    不然失去了  注册的意义

**Comment by roc-cn** [comment]
改造Dubbo，使其能够兼容Spring 4注解配置
https://my.oschina.net/roccn/blog/847635

**Comment by 15174834** [comment]
解决了
还是得多看看源码就懂了

**Comment by traburiss** [comment]
你好，请问您是怎么解决的，可以分享一下吗？ @15174834 
我看到别的地方说在application.properties添加下面这条spring.dubbo.consumer.check=false可是并没有效果。
