### ISSUE TITLE
@Reference(group = "test",timeout = 3000000)中的group的值能走配置文件吗？

### ISSUE THREAD

**Issue by mg0324** [teaey/spring-boot-starter-dubbo#313]
@Reference(group = "test",timeout = 3000000)
    private FormService formService;

**Comment by mg0324** [comment]
直接写group = "xx",不灵活，如果xx的名字变更了，代码就又得变动了。不知道有没有走application.properties的方式？

**Comment by jmdhappy** [comment]
这种配置还会经常改么

**Comment by mg0324** [comment]
改是不会经常改，但是我想从A的group切换到B的group，只能从代码修改，然后打包上传到服务器，重启生效。这样太不灵活了。

**Comment by mg0324** [comment]
注解方式不支持打包后代码修改配置，使用简单，但不灵活。我后续还是改用了dubbo的配置文件方式，这样就解决了上述问题了。

**Comment by Herm2s** [comment]
老哥请问下使用dubbo配置文件是怎么解决的
