### ISSUE TITLE
Dubbo的AnnotationBean对Class的判断有点问题

### ISSUE THREAD

**Issue by roc-cn** [teaey/spring-boot-starter-dubbo#61]
`public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
		if (!isMatchPackage(bean)) {
			return bean;
		}
		Class<?> clazz = getBeanClass(bean);
		Service service = clazz.getAnnotation(Service.class);
		// >>>>>>>>>>>>>>>>>>`

对calss的判断需要处理一下:
`private Class<?> getBeanClass(Object bean) {
		Class<?> clazz = bean.getClass();
		if (AopUtils.isAopProxy(bean)) {
			clazz = AopUtils.getTargetClass(bean);
		}
		return clazz;
	}`

**Comment by teaey** [comment]
麻烦提交下issue

**Comment by roc-cn** [comment]
@teaey 已提交到dubbo的issue
